# Custom properties
environment: prod
description: Production

# Spring configurations
spring:
  devtools:
    restart:
      enabled: false

# Logging properties
logging:
  level:
    it.carmelolagamba: INFO
    org.springframework: WARN