# Custom properties
url: localhost
server:
  port: 8080

# Kubernetes availability configuration
management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true

# OpenAI properties
springdoc:
  packagesToScan: it.carmelolagamba
  pathsToMatch: /, /*/**

# Logging properties
logging:
  level:
    root: INFO
    web: INFO