# Custom properties
url: localhost # Test variable, not used in the code, just for demonstration
server:
  port: 8080

# Kubernetes availability configuration
management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true

# OpenAI properties
springdoc:
  packagesToScan: it.carmelolagamba
  pathsToMatch: /, /*/**
